In [65]:
import pandas as pd
import numpy as np

In [66]:
player = pd.read_csv("all_seasons.csv", sep = ",")
player = player[["age", "player_height", "player_weight", "pts", "reb"]]
player = player.rename(columns = {"age": "Age", "player_height": "Height", "player_weight": "Weight", "pts": "Avg Points", "reb": "Avg Rebounds"})
player["Age"] = player["Age"].astype(int)
player["Height"] = player["Height"].astype(int)
player["Weight"] = player["Weight"].astype(int)
player["Avg Points"] = player["Avg Points"].astype(int)
player["Avg Rebounds"] = player["Avg Rebounds"].astype(int)
player.head()

Age  Height  Weight  Avg Points  Avg Rebounds
0   23     195      90           4             1
1   27     210     106           0             0
2   30     208     106           4             1
3   29     210     111           7             4
4   22     205     106           3             1

In [67]:
#player.isna().sum()

In [68]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(player[["Age" ,"Height", "Weight", "Avg Points", "Avg Rebounds"]])
z = scaler.fit_transform(player[["Age" ,"Height", "Weight", "Avg Points", "Avg Rebounds"]])
z

array([[-0.99674183, -0.58813059, -0.81730315, -0.61726116, -0.84600361],
       [-0.07727165,  1.02972208,  0.43267452, -1.29654684, -1.24475345],
       [ 0.61233098,  0.81400839,  0.43267452, -0.61726116, -0.84600361],
       ...,
       [-0.53700674,  2.10829052,  1.52640499, -0.61726116,  0.74899575],
       [-0.99674183,  1.02972208,  0.58892173,  0.06202452,  1.54649543],
       [ 0.61233098,  0.27472416,  0.1201801 ,  1.25077445,  1.14774559]])

In [69]:
player["StdAge"] = z[:,0]
player["StdHeight"] = z[:,1]
player["StdWeight"] = z[:,2]
player["StdAvg Points"] = z[:,3]
player["StdAvg Rebounds"] = z[:,4]
player.head()

Age  Height  Weight  Avg Points  Avg Rebounds    StdAge  StdHeight  \
0   23     195      90           4             1 -0.996742  -0.588131   
1   27     210     106           0             0 -0.077272   1.029722   
2   30     208     106           4             1  0.612331   0.814008   
3   29     210     111           7             4  0.382463   1.029722   
4   22     205     106           3             1 -1.226609   0.490438   

   StdWeight  StdAvg Points  StdAvg Rebounds  
0  -0.817303      -0.617261        -0.846004  
1   0.432675      -1.296547        -1.244753  
2   0.432675      -0.617261        -0.846004  
3   0.823293      -0.107797         0.350246  
4   0.432675      -0.787083        -0.846004

In [70]:
potensial = [
    {"Name" : "Andakara Prastawa Dyaksa", "Club" : "Pelita Jaya Bakrie", "Country" : "Indonesia", "Age" : 24, "Height" : 190, "Weight" : 90, "Avg Points" : 7, "Avg Rebounds" : 6},
    {"Name" : "Reggie Mononimbar", "Club" : "Pelita Jaya Bakrie", "Country" : "Indonesia", "Age" : 21, "Height" : 185, "Weight" : 86, "Avg Points" : 6, "Avg Rebounds" : 3},
    {"Name" : "Hardianus Lakudu", "Club" : "Satria Muda Pertamina Jakarta", "Country" : "Indonesia", "Age" : 23, "Height" : 178, "Weight" : 83, "Avg Points" : 10, "Avg Rebounds" : 3},
    {"Name" : "Kevin Yonas Sitorus", "Club" : "Satria Muda Pertamina Jakarta", "Country" : "Indonesia", "Age" : 26, "Height" : 185, "Weight" : 75, "Avg Points" : 11, "Avg Rebounds" : 4},
    {"Name" : "Arki Dikania Wisnu", "Club" : "Satria Muda Pertamina Jakarta", "Country" : "Indonesia", "Age" : 20, "Height" : 183, "Weight" : 80, "Avg Points" : 5, "Avg Rebounds" : 2},
    {"Name" : "Laurentius Steven Oei", "Club" : "Satria Muda Pertamina Jakarta", "Country" : "Indonesia", "Age" : 21, "Height" : 191, "Weight" : 85, "Avg Points" : 4, "Avg Rebounds" : 10},
    {"Name" : "Mei Joni", "Club" : "Stapac", "Country" : "Indonesia", "Age" : 25, "Height" : 188, "Weight" : 90, "Avg Points" : 7, "Avg Rebounds" : 5},
    {"Name" : "Vincent Rivaldi Kosasih", "Club" : "Stapac", "Country" : "Indonesia", "Age" : 23, "Height" : 179, "Weight" : 87, "Avg Points" : 1, "Avg Rebounds" : 2},
    {"Name" : "Hardian Wicaksono", "Club" : "Pacific Caesar Surabaya", "Country" : "Indonesia", "Age" : 21, "Height" : 177, "Weight" : 80, "Avg Points" : 9, "Avg Rebounds" : 8},
    {"Name" : "Brandon Jawato", "Club" : "Louvre Surabaya", "Country" : "Indonesia", "Age" : 24, "Height" : 182, "Weight" : 85, "Avg Points" : 6, "Avg Rebounds" : 5}
]

scout = pd.DataFrame(potensial)
scout = scout[["Name", "Age", "Height", "Weight", "Avg Points", "Avg Rebounds"]]
scout

Name  Age  Height  Weight  Avg Points  Avg Rebounds
0  Andakara Prastawa Dyaksa   24     190      90           7             6
1         Reggie Mononimbar   21     185      86           6             3
2          Hardianus Lakudu   23     178      83          10             3
3       Kevin Yonas Sitorus   26     185      75          11             4
4        Arki Dikania Wisnu   20     183      80           5             2
5     Laurentius Steven Oei   21     191      85           4            10
6                  Mei Joni   25     188      90           7             5
7   Vincent Rivaldi Kosasih   23     179      87           1             2
8         Hardian Wicaksono   21     177      80           9             8
9            Brandon Jawato   24     182      85           6             5

In [71]:
scout = scout[["Name", "Age", "Height", "Weight", "Avg Points", "Avg Rebounds"]]

In [72]:
scaler1 = StandardScaler()
scaler.fit(scout[["Age" ,"Height", "Weight", "Avg Points", "Avg Rebounds"]])
zz = scaler.fit_transform(scout[["Age" ,"Height", "Weight", "Avg Points", "Avg Rebounds"]])
zz

array([[ 0.63599873,  1.32911403,  1.31632171,  0.14285714,  0.48349378],
       [-0.95399809,  0.25724788,  0.42390021, -0.21428571, -0.72524067],
       [ 0.10599979, -1.24336474, -0.24541591,  1.21428571, -0.72524067],
       [ 1.69599661,  0.25724788, -2.0302589 ,  1.57142857, -0.32232919],
       [-1.48399703, -0.17149859, -0.91473203, -0.57142857, -1.12815215],
       [-0.95399809,  1.54348727,  0.20079484, -0.92857143,  2.09513971],
       [ 1.16599767,  0.90036757,  1.31632171,  0.14285714,  0.0805823 ],
       [ 0.10599979, -1.02899151,  0.64700558, -2.        , -1.12815215],
       [-0.95399809, -1.45773797, -0.91473203,  0.85714286,  1.28931674],
       [ 0.63599873, -0.38587182,  0.20079484, -0.21428571,  0.0805823 ]])

In [73]:
prospect = player[(player["Age"] <= 25) & (player["Height"] >= 180) & (player["Weight"] <= 90) & (player["Avg Points"] >= 6) & (player["Avg Rebounds"] >= 3)]
prospect.index.values

array([ 105,  290,  314,  432,  659,  835,  874, 1018, 1032, 1062, 1135,
       1141, 1332, 1351, 1436, 1515, 1516, 1720, 1727, 1748, 1875, 1951,
       2004, 2018, 2047, 2101, 2114, 2143, 2203, 2259, 2394, 2398, 2484,
       2544, 2551, 2616, 2631, 2704, 2836, 2840, 2873, 2984, 3010, 3081,
       3159, 3329, 3376, 3389, 3441, 3449, 3529, 3558, 3573, 3629, 3704,
       3717, 3721, 3830, 3994, 4036, 4039, 4068, 4121, 4124, 4252, 4267,
       4271, 4374, 4385, 4422, 4482, 4483, 4502, 4528, 4547, 4556, 4613,
       4624, 4633, 4665, 4762, 4775, 4782, 4800, 4924, 5015, 5070, 5154,
       5156, 5164, 5229, 5274, 5292, 5293, 5383, 5390, 5512, 5521, 5522,
       5548, 5587, 5609, 5675, 5743, 5747, 5820, 5914, 5952, 5954, 6001,
       6014, 6040, 6089, 6098, 6183, 6263, 6272, 6277, 6304, 6343, 6360,
       6408, 6409, 6441, 6450, 6542, 6555, 6639, 6710, 6752, 6810, 6822,
       6871, 6926, 6959, 6979, 7009, 7040, 7059, 7073, 7091, 7094, 7148,
       7184, 7199, 7305, 7306, 7342, 7365, 7369, 73

In [74]:
player["Target"] = player.apply(lambda player : 1 if (player["Age"] <= 25) and 
                                                (player["Height"] >= 180) and  
                                                (player["Weight"] <= 90) and  
                                                (player["Avg Points"] >= 6) and  
                                                (player["Avg Rebounds"] >= 3) else 0, axis = 1)
player.head()

Age  Height  Weight  Avg Points  Avg Rebounds    StdAge  StdHeight  \
0   23     195      90           4             1 -0.996742  -0.588131   
1   27     210     106           0             0 -0.077272   1.029722   
2   30     208     106           4             1  0.612331   0.814008   
3   29     210     111           7             4  0.382463   1.029722   
4   22     205     106           3             1 -1.226609   0.490438   

   StdWeight  StdAvg Points  StdAvg Rebounds  Target  
0  -0.817303      -0.617261        -0.846004       0  
1   0.432675      -1.296547        -1.244753       0  
2   0.432675      -0.617261        -0.846004       0  
3   0.823293      -0.107797         0.350246       0  
4   0.432675      -0.787083        -0.846004       0

### Logistic Regression (Splitting per model)

In [88]:
from sklearn.model_selection import train_test_split
xtr,xts,ytr,yts = train_test_split(player[['Age','Height','Weight', "Avg Points", "Avg Rebounds"]], player['Target'], test_size = .18)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(solver = "lbfgs")
print(model.fit(xtr,ytr))
print(model.score(xts,yts))

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)
0.9779198140615921


In [76]:
penalty = ["l2"]
solver = ["newton-cg", "lbfgs", "liblinear", "sag", "saga"]
max_iter = [1, 10, 100, 1000, 10000]

param = {"penalty": penalty, "solver": solver, "max_iter" : max_iter}
model.get_params()

{'C': 1.0,
 'class_weight': None,
 'dual': False,
 'fit_intercept': True,
 'intercept_scaling': 1,
 'l1_ratio': None,
 'max_iter': 100,
 'multi_class': 'warn',
 'n_jobs': None,
 'penalty': 'l2',
 'random_state': None,
 'solver': 'lbfgs',
 'tol': 0.0001,
 'verbose': 0,
 'warm_start': False}

In [77]:
from sklearn.model_selection import RandomizedSearchCV
model = LogisticRegression()
modelrs = RandomizedSearchCV(estimator = model, param_distributions = param, cv = 5)
modelrs.fit(xtr, ytr)
modelrs.best_params_

C:\Users\User\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarning)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:947: ConvergenceWarning: lbfgs failed to converge. Increase the number of iterations.
  "of iterations.", ConvergenceWarn

{'solver': 'newton-cg', 'penalty': 'l2', 'max_iter': 10000}

In [78]:
modelHPTLR = LogisticRegression(solver = "newton-cg", penalty = "l2", max_iter = 10000)
print(modelHPTLR.fit(xtr,ytr))
print(modelHPTLR.score(xts,yts))

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=10000,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='newton-cg', tol=0.0001, verbose=0,
                   warm_start=False)
0.9808251016850669


### Evaluation Metrics

In [100]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import roc_auc_score
ypred = model.predict(xts)
print(balanced_accuracy_score(yts, ypred))
print(precision_score(yts, ypred))
print(recall_score(yts, ypred))
print(f1_score(yts, ypred))
print(roc_auc_score(yts, ypred))
print(ypred[:10])
print(yts[:10])

0.7009676370141487
0.6
0.4090909090909091
0.4864864864864865
0.7009676370141487
[0 0 0 0 0 0 0 0 0 0]
8431    0
3407    0
2089    0
8913    0
1541    0
5466    0
8215    0
44      0
2740    0
3934    0
Name: Target, dtype: int64


### Decision Tree (Splitting per model)

In [101]:
from sklearn.model_selection import train_test_split

xtr,xts,ytr,yts = train_test_split(player[['Age','Height','Weight', "Avg Points", "Avg Rebounds"]], player['Target'], test_size = .18)

from sklearn import tree

model1 = tree.DecisionTreeClassifier()
print(model1.fit(xtr,ytr))
print(model1.score(xts,yts))

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')
1.0


In [80]:
model1.get_params

<bound method BaseEstimator.get_params of DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')>

In [81]:
param2 = {"class_weight" : [None], 
          "criterion" : ['gini'], 
          "max_depth" : [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, None] ,
          "max_features" : [None], 
          "max_leaf_nodes" : [None],
          "min_impurity_decrease" : [0.0], 
          "min_impurity_split" : [None],
          "min_samples_leaf" : [1], 
          "min_samples_split" : [2],
          "min_weight_fraction_leaf" : [0.0], 
          "presort" : [True, False],
          "random_state" : [None], 
          "splitter": ['best']}

In [82]:
modelrs = RandomizedSearchCV(estimator = model1, param_distributions = param2, cv = 5)
modelrs.fit(xtr, ytr)
modelrs.best_params_

{'splitter': 'best',
 'random_state': None,
 'presort': False,
 'min_weight_fraction_leaf': 0.0,
 'min_samples_split': 2,
 'min_samples_leaf': 1,
 'min_impurity_split': None,
 'min_impurity_decrease': 0.0,
 'max_leaf_nodes': None,
 'max_features': None,
 'max_depth': 100,
 'criterion': 'gini',
 'class_weight': None}

In [83]:
modelHPTDT = tree.DecisionTreeClassifier(splitter = "best", random_state = None, presort = False, min_weight_fraction_leaf = 0.0,
                                         min_samples_split = 2, min_samples_leaf = 1, min_impurity_split = None, min_impurity_decrease = 0.0,
                                         max_leaf_nodes = None, max_features = None, max_depth = 80, criterion = 'gini',
                                         class_weight = None)
print(modelHPTDT.fit(xtr,ytr))
print(modelHPTDT.score(xts,yts))

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=80,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')
1.0


### Evaluation Metrics

In [102]:
ypred = model1.predict(xts)
print(balanced_accuracy_score(yts, ypred))
print(precision_score(yts, ypred))
print(recall_score(yts, ypred))
print(f1_score(yts, ypred))
print(roc_auc_score(yts, ypred))
print(ypred[:10])
print(yts[:10])

1.0
1.0
1.0
1.0
1.0
[0 0 0 0 0 0 0 0 0 0]
7674    0
7970    0
4060    0
8218    0
8676    0
7788    0
1359    0
9254    0
9211    0
9559    0
Name: Target, dtype: int64


### Random Forest (Splitting per model)

In [105]:
from sklearn.model_selection import train_test_split

xtr,xts,ytr,yts = train_test_split(player[['Age','Height','Weight', "Avg Points", "Avg Rebounds"]], player['Target'], test_size = .18)

from sklearn.ensemble import RandomForestClassifier

model2 = RandomForestClassifier(n_estimators = 100, max_depth = 2)
print(model2.fit(xtr,ytr))
print(model2.score(xts,yts))

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=2, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)
0.9773387565368972


In [85]:
param1 = {'bootstrap': [True, False],
          'max_depth': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, None],
          'max_features': ['auto', 'sqrt'],
          'min_samples_leaf': [1, 2, 4],
          'min_samples_split': [2, 5, 10],
          'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000]}
model2.get_params()

{'bootstrap': True,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': 2,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [86]:
modelrs = RandomizedSearchCV(estimator = model2, param_distributions = param1, cv = 5)
modelrs.fit(xtr, ytr)
modelrs.best_params_

KeyboardInterrupt: 

In [42]:
modelHPTRF = RandomForestClassifier(n_estimators = 2000, min_samples_split = 10, min_samples_leaf = 1, max_features = "sqrt", max_depth = 100, bootstrap = "False")
print(modelHPTRF.fit(xtr,ytr))
print(modelHPTRF.score(xts,yts))

RandomForestClassifier(bootstrap='False', class_weight=None, criterion='gini',
                       max_depth=100, max_features='sqrt', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=10,
                       min_weight_fraction_leaf=0.0, n_estimators=2000,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)
1.0


### Evaluation Metrics

In [106]:
ypred = model2.predict(xts)
print(balanced_accuracy_score(yts, ypred))
print(precision_score(yts, ypred))
print(recall_score(yts, ypred))
print(f1_score(yts, ypred))
print(roc_auc_score(yts, ypred))
print(ypred[:10])
print(yts[:10])

0.5
0.0
0.0
0.0
0.5
[0 0 0 0 0 0 0 0 0 0]
5895    0
1603    0
4768    0
2959    0
8356    0
3538    0
3151    0
8092    0
9036    0
1870    0
Name: Target, dtype: int64


C:\Users\User\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\User\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1437: UndefinedMetricWarning: F-score is ill-defined and being set to 0.0 due to no predicted samples.
  'precision', 'predicted', average, warn_for)


### Karena paling besar score dari Decision Tree, maka kita pakai model Decision Tree yang sudah di Hypertuning

In [107]:
scout["Recommendation"] = modelHPTDT.predict(scout[["Age", "Height", "Weight", "Avg Points", "Avg Rebounds"]])
scout

Name  Age  Height  Weight  Avg Points  Avg Rebounds  \
0  Andakara Prastawa Dyaksa   24     190      90           7             6   
1         Reggie Mononimbar   21     185      86           6             3   
2          Hardianus Lakudu   23     178      83          10             3   
3       Kevin Yonas Sitorus   26     185      75          11             4   
4        Arki Dikania Wisnu   20     183      80           5             2   
5     Laurentius Steven Oei   21     191      85           4            10   
6                  Mei Joni   25     188      90           7             5   
7   Vincent Rivaldi Kosasih   23     179      87           1             2   
8         Hardian Wicaksono   21     177      80           9             8   
9            Brandon Jawato   24     182      85           6             5   

   Recommendation  
0               1  
1               1  
2               0  
3               0  
4               0  
5               0  
6               1  
7               0  
8               0  
9               1